# Generated by Django 3.2.16 on 2022-10-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='qwert', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
